language: php

php:
  - 7.2
  - 7.3

before_install:
  - sudo apt-get update
  - sudo apt-get install libv8-dev g++ cpp valgrind libxml2-dev -y
  - printf "\n" | pecl install v8js-2.1.1
  - phpenv config-add travis.php.ini
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script: valgrind --trace-children=yes vendor/bin/phpunit --debug --verbose
